### ISSUE TITLE
If a secret doesn't exist but is attached to a service account, it is still listed by kp secret list

### ISSUE THREAD

**Issue by tylerphelan** [buildpacks-community/kpack-cli#214]
We could handle this better

**Comment by fcaroline2020** [comment]
```
$ kubectl delete secret -n test tutorial-registry-credentials
$ kp secret list -n test                               
NAME                             TARGET
tutorial-registry-credentials    https://index.docker.io/v1/
```

What behavior would make the most sense?
- Error message listing the missing secrets
- Additional column "AVAILABLE" with true / false
- other....?

**Comment by fcaroline2020** [comment]
Output before

`NAME                                     TARGET
test-secret                               https://index.docker.io/v1/
tutorial-registry-credentials    https://index.docker.io/v1/`

Output after

`
NAME                                      TARGET                                 AVAILABLE
test-secret                               https://index.docker.io/v1/    false
tutorial-registry-credentials    https://index.docker.io/v1/    true
`

**Comment by tomkennedy513** [comment]
My understanding is that kp will just print all the secrets from the `kpack.io/managedSecret` label on the serviceAccount which may contain secrets that no longer exist. Maybe the best thing to do here would be to reconcile that managedSecret before we attempt to print it to make sure its up to date

**Comment by fcaroline2020** [comment]
I also considered updating the service account to remove the secrets that were not available anymore but decided against it because if I am doing` kp secret list` I would not expect the command to edit the service account.

**Comment by tomkennedy513** [comment]
maybe we should log an error then? I think part of the issue is that entry in the service account is something we own so im not sure at one point it would be cleaned up if the secret got deleted without using kp. If you try to use that service account for a build it will likely fail since the secret won't exist.

**Comment by fcaroline2020** [comment]
We could add an `kp secret list --update` flag which would remove all secrets that do not exist.

**Comment by chenbh** [comment]
I would print out an error message, something like `Warning: secret "abc" is attached to the service account but could not be found in namespace "xyz"` for each missing secret. But I'm fine with the `AVAILABLE: true/false` approach as well.

**Comment by chenbh** [comment]
But I also see `kp secret list` as kinda fundamentally flawed because it only looks at the default service account. The way the command is worded makes me feel like it should operate on the namespace rather than service accounts.

We should either:
- provide it a `--service-account` flag to specify which service account to look at
- list all the kpack secrets (i.e. those with `kpack.io/*` annotation) in the given namespace (and maybe map it to service account(s) if possible)

**Comment by fcaroline2020** [comment]
The --service-account flag is there where the default is the "default" service account.

I've kept the AVAILABLE: true/false approach instead of the error message.

**Comment by chenbh** [comment]
> The --service-account flag is there where the default is the "default" service account.

Whoops, I completely missed that bit of code
